name: nmobile
description: nMobile

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# 21/04/26 last by HaoNan
# version: 1.1.2+223
# 21/07/XX test ios notification
# version: 1.2.0+224
# 21/08/XX
# version: 1.2.0+225
# 21/09/XX
# version: 1.2.0+226
# 21/09/29
# version: 1.2.0+227
# 21/10/01
# version: 1.2.0+228
# 21/10/08
# version: 1.2.0+229
# 21/10/12
# version: 1.2.0+230
# 21/10/13
# version: 1.2.0+231
# 21/10/18
# version: 1.2.0+232
# 21/10/27
# version: 1.2.0+233
# 21/10/28
# version: 1.2.0+234
# 21/10/29
# version: 1.2.0+235
# 21/10/30
# version: 1.2.0+236
# 21/11/01
# version: 1.2.0+237
# 21/11/07
# version: 1.2.0+238
# 21/11/10
# version: 1.2.0+239
# 21/11/11
# version: 1.2.0+240
# 21/11/12
# version: 1.2.0+241
# 21/11/13
# version: 1.2.0+242
# 21/11/14
# version: 1.2.0+243
# 21/11/15
# version: 1.2.0+244
# 21/11/16
# version: 1.2.0+245
# 21/11/23
# version: 1.2.1+246
# 21/11/23
# version: 1.2.1+247
# 21/11/24
# version: 1.2.1+249
# 21/01/14
# version: 1.2.2+250
# 21/01/15
# version: 1.2.3+251
# 21/02/22
#version: 1.2.4+252
# 21/02/28
version: 1.2.5+253

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # flutter_plugins
  image_picker: ^0.8.4
  local_auth: ^1.1.7
  package_info_plus: ^1.0.6
  device_info_plus: ^2.1.0
  share_plus: ^2.1.4
  connectivity_plus: ^2.2.0
  path_provider: ^2.0.3
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.2
  #  webview_flutter: ^2.0.12

  # common
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  synchronized: ^3.0.0
  dio: ^4.0.0
  get_it: ^7.2.0
  uuid: ^3.0.4
  crypto: ^3.0.1
  mime_type: ^1.0.0
  permission_handler: ^8.1.6
  vibration: ^1.7.3
  flutter_local_notifications: ^8.2.0
  background_fetch: ^1.0.1
  #  get: ^4.3.8
  #  provider: ^6.0.0
  #  auto_route: ^2.3.0
  #  flutter_aes_ecb_pkcs5: ^0.1.1

  # log
  logger: ^1.1.0
  sentry_flutter: ^6.0.1

  # locale
  intl: ^0.17.0
  flutter_cupertino_localizations: ^1.0.1

  # storage
  flutter_secure_storage: ^4.2.1
  sqflite: ^2.0.0+4
  sqflite_sqlcipher: ^2.0.0
  #  hive: ^2.0.4

  # UI
  flutter_screenutil: ^5.0.0+2
  animations: ^2.0.1
  bot_toast: ^4.0.1
  flutter_spinkit: ^5.1.0
  flutter_markdown: ^0.6.6
  flutter_slidable: ^0.6.0
  #  flutter_screenutil: ^5.0.0+2
  #  flutter_native_splash: ^1.2.2
  #  fluttertoast: ^8.0.8
  #  fl_chart: ^0.40.0
  #  auto_size_text: ^2.1.0
  #  flutter_swiper: ^1.1.6
  #  modal_bottom_sheet: ^2.0.0
  #  badges: ^2.0.1
  #  timeline_tile: ^2.0.0

  # list
  #  pull_to_refresh: ^2.0.0
  #  infinite_scroll_pagination: ^3.1.0
  #  flutter_staggered_grid_view: ^0.4.0

  # icon
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  cupertino_icons: ^1.0.3

  # file
  path: ^1.8.0
  file_picker: ^4.0.3

  # image
  photo_view: ^0.12.0
  flutter_image_compress: ^1.0.0
  image_cropper: ^1.4.1
  #  flutter_luban: ^0.1.13
  #  wechat_assets_picker: ^6.1.1
  #  octo_image: ^1.0.0+1

  # audio
  flutter_sound: ^8.3.10
  #  audioplayers: ^0.19.1
  #  just_audio: ^0.9.10

  # video
  #  video_player: ^2.1.15

  # QR
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0

  # eth
  web3dart: ^2.3.1

  # plugins
  nkn_sdk_flutter:
    path: ./plugins/nkn-sdk-flutter

#dependency_overrides:
#  sqflite:
#    git:
#      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
#      path: sqflite
#      ref: fmdb_override

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/contact/
    - assets/icons/
    - assets/chat/
    - assets/wallet/
    - assets/splash/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
